version: '3.7'

services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: node server.js
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb+srv://ameerhamza963:Eo0mIqr2IvOkn7Yl@cluster0.ylla0w5.mongodb.net/
      - NODE_ENV=development


  client:
    build:
      context: ./Web
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm run start
    ports:
      - '3000:3000'    
    environment:
      - REACT_APP_API_URL=http://ec2-54-226-103-25.compute-1.amazonaws.com:4000
    depends_on:
      - server

volumes:
  data-volume:
  web-root:
    driver: local
